### ISSUE TITLE
앱 로고 비율이 맞지 않아요

### ISSUE THREAD

**Issue by HongSJae** [team-osj/Loutra-Flutter#6]
이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다이거 안고치면 게이썬으로 알고리즘 풉니다

**Comment by Yoochanhong** [comment]
빠르게 수정하겠습니다.

**Comment by Yoochanhong** [comment]
~~어쩌라고 ^^l~~
안녕하세요 HongSJae님! 저희 앱을 사용해주셔서 감사합니다.

앱 로고가 맞지 않아 앱 사용중 불편함을 겪으셨군요 ㅠㅠ 어쩔건데 걍 써

라고 하면 게이썬으로 문제를 풀게 뻔하니 사진은 제가 가로세로 비율을 맞춰 조절해서 다시 올리도록 하겠습니다

더더욱 발전하는 OSJ가 되겠습니다 감사합니다!
