### ISSUE TITLE
Alert 버튼 iOS 같지 않습니다

### ISSUE THREAD

**Issue by HongSJae** [team-osj/Loutra-Flutter#7]
Label이 아닌 버튼 자체를 누르면 입력되며 기존 iOS Alert를 확인해보시며 재 개발 해주시면 좋을 것 같습니다.
![image](https://github.com/team-osj/Loutra-Flutter/assets/102791216/1742f284-a821-4ae0-9249-477d47f01fa8)

**Comment by Yoochanhong** [comment]
HongSJae님! 피드백 해주셔서 감사합니다.

현재 Alert에 들어가는 버튼은 TextButton으로 글자만큼의 버튼 크기를 가지고 있어 옆 여백을 누르면 적용이 안되는 불편함이 있습니다.

현재 개발팀도 그 부분을 인지하고 있으며, 빠른 시일 내에 변경할 예정입니다.

관심 가져주셔서 감사합니다!

**Comment by Yoochanhong** [comment]
@HongSJae 알잘딱으로 해놨음 ㅇㅇ 업데이트 할때 검수 바람 ^_^

**Comment by HongSJae** [comment]
언제 업뎃 하나요?

**Comment by Yoochanhong** [comment]
알림 신청한 기기들 목록을 볼수 있는 리스트 기능을 구현중이라 시간이 조금 걸릴 것 같습니다;
